/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package exercicio;

import java.time.Clock;
import javax.swing.JOptionPane;

/**
 *
 * @author Biel
 */
public class Principal extends javax.swing.JFrame {

    /** Creates new form Principal */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtValores = new javax.swing.JTextField();
        rBubble = new javax.swing.JRadioButton();
        rInsertion = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        txtResultado = new javax.swing.JLabel();
        txtTempo = new javax.swing.JLabel();
        rCountingSort = new javax.swing.JRadioButton();
        rSelection = new javax.swing.JRadioButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtConjunto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtBusca = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        rSequencial = new javax.swing.JRadioButton();
        rBinario = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        lblVetor = new javax.swing.JLabel();
        lblEncontrado = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtValorN = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        txtProcessamento = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Conjunto de números: ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        txtValores.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(txtValores, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 420, 30));

        buttonGroup1.add(rBubble);
        rBubble.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rBubble.setText("Bubble");
        jPanel2.add(rBubble, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 77, -1));

        buttonGroup1.add(rInsertion);
        rInsertion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rInsertion.setText("Insertion");
        jPanel2.add(rInsertion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton2.setText("Ordenar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 100, 40));

        txtResultado.setBackground(new java.awt.Color(255, 255, 255));
        txtResultado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtResultado.setForeground(new java.awt.Color(0, 153, 102));
        txtResultado.setText("[]");
        jPanel2.add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 700, -1));

        txtTempo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTempo.setForeground(new java.awt.Color(0, 153, 102));
        txtTempo.setText("Tempo de Execução");
        jPanel2.add(txtTempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        buttonGroup1.add(rCountingSort);
        rCountingSort.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rCountingSort.setText("Counting Sort");
        jPanel2.add(rCountingSort, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        buttonGroup1.add(rSelection);
        rSelection.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rSelection.setText("Selection");
        jPanel2.add(rSelection, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton5.setText("Gerar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 100, 40));

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton6.setText("Limpar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 100, 40));

        jTabbedPane1.addTab("Ordenação", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Conjunto de números: ");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 41, -1, -1));

        txtConjunto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(txtConjunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 31, 420, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Buscar número");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 72, -1, -1));
        jPanel3.add(txtBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 70, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 90, 40));

        buttonGroup2.add(rSequencial);
        rSequencial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rSequencial.setText("Sequencial");
        rSequencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSequencialActionPerformed(evt);
            }
        });
        jPanel3.add(rSequencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        buttonGroup2.add(rBinario);
        rBinario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rBinario.setText("Binária");
        rBinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBinarioActionPerformed(evt);
            }
        });
        jPanel3.add(rBinario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton4.setText("Limpar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 90, 40));

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton8.setText("Gerar");
        jButton8.setToolTipText("");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 90, 40));

        lblVetor.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblVetor.setForeground(new java.awt.Color(0, 153, 102));
        lblVetor.setText("[ ]");
        jPanel3.add(lblVetor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 640, -1));

        lblEncontrado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEncontrado.setForeground(new java.awt.Color(0, 153, 102));
        jPanel3.add(lblEncontrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 430, 30));

        jTabbedPane1.addTab("Busca", jPanel3);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Valor de N:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Complexidade: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        txtValorN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtValorN, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 110, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 120, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Processamento: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        lblResultado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblResultado.setForeground(new java.awt.Color(0, 153, 102));
        jPanel1.add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 204, -1, -1));

        txtProcessamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txtProcessamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 110, 30));

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton7.setText("Limpar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 120, 40));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 110, 30));

        jTabbedPane1.addTab("Complexidade", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        float valorN = Float.parseFloat(txtValorN.getText());
        float processamento = Float.parseFloat(txtProcessamento.getText());
        float resultado = (float) (2 * Math.pow(valorN,2)/processamento);
        lblResultado.setText(Float.toString(resultado));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:        
        
        if (this.txtValores.getText().length() < 1){
            JOptionPane.showMessageDialog(null, "Erro! Digite os valores na caixa de texto!");
        }else{
        var txtVetor = this.txtValores.getText();
        
        if (this.rBubble.isSelected()){
            var resultado = Ordenar.OrdenarPorBubbleSort(txtVetor);
            this.txtResultado.setText("[ " + resultado.getNumeros()+ " ]");
            this.txtTempo.setText(resultado.getTempoExecucao() + " Nanosegundos");
        }
        
        if (this.rInsertion.isSelected()){
            var resultado = Ordenar.OrdenarPorInsertionSort(txtVetor);
            this.txtResultado.setText("[ " + resultado.getNumeros()+ " ]");
            this.txtTempo.setText(resultado.getTempoExecucao() + " Nanosegundos");
        }
        
        if (this.rSelection.isSelected()){
            var resultado = Ordenar.OrdenarPorSelectionSort(txtVetor);
            this.txtResultado.setText("[ " + resultado.getNumeros()+ " ]");
            this.txtTempo.setText(resultado.getTempoExecucao() + " Nanosegundos");
        }
        
        if (this.rCountingSort.isSelected()){
            var resultado = Ordenar.OrdenarPorCountingSort(txtVetor);
            this.txtResultado.setText("[ " + resultado.getNumeros()+ " ]");
            this.txtTempo.setText(resultado.getTempoExecucao() + " Nanosegundos");
        }
            
        }        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.txtValores.setText(LerValores.GerarValores());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.txtValores.setText("");
        this.txtTempo.setText("");
        this.txtResultado.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       if(this.txtConjunto.getText() == null || !this.rBinario.isSelected() && !this.rSequencial.isSelected()){
           JOptionPane.showMessageDialog(null, "Erro!");
       }else{
           
       if(this.rSequencial.isSelected()){
           var resultado = Busca.BuscaSequencial(LerValores.LerNumeros(txtConjunto.getText()), txtBusca.getText());       
           this.lblEncontrado.setText(resultado.resultado);
       }
       if(this.rBinario.isSelected()){
           this.lblEncontrado.setText("Valor não encontrado");
           var txtNumeros = LerValores.LerNumeros(txtConjunto.getText());
           var intNumeros = LerValores.ConverterEmInteiro(txtNumeros);
           var numerosOrdenados = Ordenar.CountingSort(intNumeros);
           this.lblVetor.setText("[ " + LerValores.ConverterVetorEmString(LerValores.ConverterEmString(numerosOrdenados))+" ]");
           var encontrado = Busca.BuscaBinaria(numerosOrdenados, Integer.parseInt(txtBusca.getText()));
           if (encontrado.getResultado() != null) this.lblEncontrado.setText(encontrado.getResultado());
           
       }
       }
        

    }//GEN-LAST:event_jButton3ActionPerformed
 
    private void rSequencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSequencialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSequencialActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.txtConjunto.setText("");
        this.txtBusca.setText("");
        this.lblVetor.setText("[ ]");
        this.lblEncontrado.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        this.txtValorN.setText("");
        this.txtProcessamento.setText("");
        this.lblResultado.setText("");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void rBinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBinarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rBinarioActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        this.txtConjunto.setText(LerValores.GerarValores());
    }//GEN-LAST:event_jButton8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblEncontrado;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblVetor;
    private javax.swing.JRadioButton rBinario;
    private javax.swing.JRadioButton rBubble;
    private javax.swing.JRadioButton rCountingSort;
    private javax.swing.JRadioButton rInsertion;
    private javax.swing.JRadioButton rSelection;
    private javax.swing.JRadioButton rSequencial;
    private javax.swing.JTextField txtBusca;
    private javax.swing.JTextField txtConjunto;
    private javax.swing.JTextField txtProcessamento;
    private javax.swing.JLabel txtResultado;
    private javax.swing.JLabel txtTempo;
    private javax.swing.JTextField txtValorN;
    private javax.swing.JTextField txtValores;
    // End of variables declaration//GEN-END:variables

}
